feat: add pagination in subcategory
Monday-Morning/project-tahiti pull request #192
Opened 2022-05-10 14:32 UTC by 120EE0692

### Your checklist for this pull request

🚨Please review the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [ ] Make sure you are making a pull request against the **default branch** (left side). Also you should start _your branch_ off _default branch_.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.
- [ ] I have added necessary documentation (if appropriate)

### Linked Issues

Fixes

### Description

add pagination in the subcategory page.
<img width="943" alt="image" src="https://user-images.githubusercontent.com/83752052/167653297-65d5061f-51f5-4335-af35-03bebbb60dc0.png">
<img width="262" alt="image" src="https://user-images.githubusercontent.com/83752052/167653749-89b0c357-cb78-447d-8ae9-78a7f9e7090f.png">

❤️Thank you!

### Post merge checklist

- [ ] Follow steps from the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2022-05-13 18:10 UTC, rutajdash requested changes
Whatever processing can be done server side, do it there.

2022-05-13 18:10 UTC, rutajdash commented on client/src/graphql/queries/subcategory/countOfArticlesBySubCategory.js
> +`;
Fix the formatting errors

2022-05-13 18:10 UTC, rutajdash commented on client/src/pages/[category]/[subCategory].jsx
> +  }, [pageNo])
This can easily be handled in getStaticProps, why shift here?

2022-05-13 18:10 UTC, rutajdash commented on client/src/screens/SubCategory.js
> +}))
Add empty line at end of file

2022-05-14 04:13 UTC, 120EE0692 commented on client/src/screens/SubCategory.js
> +}))
add empty line

2022-05-14 04:13 UTC, 120EE0692 commented on client/src/graphql/queries/subcategory/countOfArticlesBySubCategory.js
> +`;
formatted

2022-05-14 04:14 UTC, 120EE0692 commented on client/src/pages/[category]/[subCategory].jsx
> +  }, [pageNo])
initial data now handled in getStaticProps

2022-05-14 08:21 UTC, rutajdash commented
@120EE0692 rebase with latest changes once, will review then.

2022-05-14 09:22 UTC, rutajdash requested changes
You have overwritten the changes made in #194 .
Fix it.

2022-05-14 09:22 UTC, rutajdash commented on client/src/pages/[category]/[subCategory].jsx
>      categoryName.toUpperCase()
You have overwritten the changes made in #194 .
Fix this.

2022-05-14 09:22 UTC, rutajdash commented on client/src/pages/[category]/[subCategory].jsx
> +    .filter(({ shortName }) => shortName === subCategory)[0];
Formatting errors here. Fix.

2022-05-14 09:22 UTC, rutajdash commented on client/src/pages/[category]/[subCategory].jsx
> +          data: { getArticlesByCategories: articleList },
Clash in variable name, use a different one.

2022-05-14 09:22 UTC, rutajdash commented on client/src/pages/[category]/[subCategory].jsx
> +  }, [pageNo])
ESLINT: Add the proper dependencies to useEffect

2022-05-14 09:22 UTC, rutajdash commented on client/src/pages/[category]/[subCategory].jsx
>        categoryNumbers: [subCategoryDetails.idNumber],
You have overwritten the changes made in #194  .
Fix this.

2022-05-14 14:16 UTC, rutajdash approved these changes

2022-05-14 14:18 UTC, merged