feat: add expression and expression subcategory page
Monday-Morning/project-tahiti pull request #233
Opened 2022-06-19 10:26 UTC by 120EE0692

### Your checklist for this pull request

🚨Please review the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [x] Make sure you are making a pull request against the **default branch** (left side). Also you should start _your branch_ off _default branch_.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.
- [x] I have added necessary documentation (if appropriate)

### Linked Issues

Fixes

### Description

add expression and expression subcategory page
Only wisdom, Editorial and Miscellaneous were added.
Remaining will be added later.

❤️Thank you!

### Post merge checklist

- [x] Follow steps from the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.
- [x] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2022-07-03 14:56 UTC, rutajdash reviewed
@120EE0692
I recommend having a custom subcategory filter (in the getStaticProps section) for the catch-all file as we have varied non-article subcategories in the editorial. Also, consider if a catch-all would work here since the UI may differ for each.

2022-07-03 15:44 UTC, rutajdash commented
![image](https://user-images.githubusercontent.com/33367546/177047065-9f3bfd20-e20b-4026-9c8b-1f91396eea49.png)
@120EE0692 ?

2022-07-03 16:14 UTC, 120EE0692 commented
> @120EE0692 I recommend having a custom subcategory filter (in the getStaticProps section) for the catch-all file as we have varied non-article subcategories in the editorial. Also, consider if a catch-all would work here since the UI may differ for each.

Non-article subcategories are yet not prepared.

2022-07-03 16:14 UTC, 120EE0692 commented
> ![image](https://user-images.githubusercontent.com/33367546/177047065-9f3bfd20-e20b-4026-9c8b-1f91396eea49.png) @120EE0692 ?

<img width="607" alt="image" src="https://user-images.githubusercontent.com/83752052/177048145-ce985449-1c5c-424a-93a4-a1a0266f5f6f.png">

2022-07-04 06:48 UTC, rutajdash commented
> > @120EE0692 I recommend having a custom subcategory filter (in the getStaticProps section) for the catch-all file as we have varied non-article subcategories in the editorial. Also, consider if a catch-all would work here since the UI may differ for each.
> 
> Non-article subcategories are yet not prepared.

I understand, however, it is better to have the filter from now itself. And display not-found for others.

2022-07-04 07:19 UTC, rutajdash commented
> > ![image](https://user-images.githubusercontent.com/33367546/177047065-9f3bfd20-e20b-4026-9c8b-1f91396eea49.png) @120EE0692 ?
> 
> <img alt="image" width="607" src="https://user-images.githubusercontent.com/83752052/177048145-ce985449-1c5c-424a-93a4-a1a0266f5f6f.png">
> 
> @rutajdash

The error is still persisting in a clean environment, please see what is the issue.

2022-07-04 10:06 UTC, 120EE0692 commented
> > > ![image](https://user-images.githubusercontent.com/33367546/177047065-9f3bfd20-e20b-4026-9c8b-1f91396eea49.png) @120EE0692 ?
> > 
> > 
> > <img alt="image" width="607" src="https://user-images.githubusercontent.com/83752052/177048145-ce985449-1c5c-424a-93a4-a1a0266f5f6f.png">
> > @rutajdash
> 
> The error is still persisting in a clean environment, please see what is the issue.

@rutajdash 
<img width="610" alt="image" src="https://user-images.githubusercontent.com/83752052/177132239-7feda46d-ace8-4cde-8b47-e043233b5229.png">
When I am using this this is working fine. 

As I noticed in the production database the podcast and editorial subcategory, numbers get swapped. Hence I also change in app. Maybe in this link https://project-reclamation-staging.herokuapp.com/v1/graph the number may not get swapped, and hence when it makes the request for the editorial it get a null response.

2022-08-28 12:16 UTC, rutajdash requested changes

2022-08-28 12:16 UTC, rutajdash commented on client/src/pages/expressions/[subCategory].jsx
> +  let routes = ROUTES.SUB_CATEGORIES.ARRAY[5];
```suggestion
  let routes = ROUTES.SUB_CATEGORIES.OBJECT.EXPRESSIONS;
```

2022-08-28 12:17 UTC, rutajdash approved these changes

2022-08-28 12:17 UTC, merged