feat: replace old portfolio
Monday-Morning/project-tahiti pull request #240
Opened 2022-07-22 12:36 UTC by 120EE0692

### Your checklist for this pull request

🚨Please review the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [x] Make sure you are making a pull request against the **default branch** (left side). Also you should start _your branch_ off _default branch_.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.
- [x] I have added necessary documentation (if appropriate)

### Description
Activate the user old portfolio page in new website

❤️Thank you!

### Post merge checklist

- [ ] Follow steps from the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2022-07-23 18:05 UTC, rutajdash requested changes
Ensure the following:
1. If someone opens a profile page which is `/portfolio/<newUserId>`, redirect it to `/portfolio/<newUserId>/<generatedUserName`
2. If someone opens a profile page which is `/portfolio/<newUserId>/<invalidUserName>`, redirect it to `/portfolio/<newUserId>/<generatedUserName`
3. The generatedUserName must be `<firstName>_<lastName>`
4. If anyone opens `/portfolio/<oldUserName>`, redirect it to `/portfolio/<newUserId>/<generatedUserName`
5. If anyone has an Email Id as `transfer-<something>@gmail.com`, do not show any email ID.

2022-07-23 18:05 UTC, rutajdash commented on client/src/pages/portfolio/[userId].jsx
> +  }
Let a profile exist for both these accounts

2022-07-24 01:47 UTC, 120EE0692 commented on client/src/pages/portfolio/[userId].jsx
> +  }
Such profiles have 150+ articles. We have to implement pagination for this. Which I planned to do later.

2022-07-24 01:49 UTC, 120EE0692 commented on client/src/pages/portfolio/[userId]/[name].jsx
> +  const noOfArticle = articleList.length;
I made a wrong assumption that a author have not written more than 40 articles. 
And hence few of the portfolio are not working.

2022-07-24 09:02 UTC, rutajdash commented
@120EE0692 Tag me and let me know once the following is done.

> Ensure the following:
> 
> 1. If someone opens a profile page which is `/portfolio/<newUserId>`, redirect it to `/portfolio/<newUserId>/<generatedUserName`
> 2. If someone opens a profile page which is `/portfolio/<newUserId>/<invalidUserName>`, redirect it to `/portfolio/<newUserId>/<generatedUserName`
> 3. The generatedUserName must be `<firstName>_<lastName>`
> 4. If anyone opens `/portfolio/<oldUserName>`, redirect it to `/portfolio/<newUserId>/<generatedUserName`
> 5. If anyone has an Email Id as `transfer-<something>@gmail.com`, do not show any email ID.

2022-08-23 18:40 UTC, rutajdash commented
@120EE0692 please complete the mentioned tasks.

2022-08-27 11:04 UTC, rutajdash requested changes
1. User slug check logic is inefficient.
2. Unnecessary details in getUserByOldUserName

2022-08-27 16:47 UTC, rutajdash approved these changes

2022-08-27 16:48 UTC, merged