Fix : Updated the terms and services content
Monday-Morning/project-tahiti pull request #259
Opened 2022-09-08 16:42 UTC by anish-patro

### Your checklist for this pull request

🚨Please review the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [ ] Make sure you are making a pull request against the **default branch** (left side). Also you should start _your branch_ off _default branch_.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.
- [ ] I have added necessary documentation (if appropriate)

### Linked Issues

Fixes

### Description

Please describe your pull request.

❤️Thank you!

### Post merge checklist

- [ ] Follow steps from the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2022-09-20 10:26 UTC, rutajdash commented
@120EE0692 @sambit-sankalp please perform a preliminary review.

2022-10-01 11:45 UTC, sambit-sankalp commented
Hey @anish-patro ,
This PR seems nice, but few changes
- Make sure to update the meta tags and OpenGraph of the policy page in the page directory.
- Make sure to add the coming soon redirect on the policy page.

2022-10-01 11:46 UTC, sambit-sankalp requested changes
Hey @anish-patro ,
This PR seems nice, but few changes

- Make sure to update the meta tags and OpenGraph of the policy page in the page directory.
- Make sure to add the coming soon redirect on the policy page.

2022-10-16 12:10 UTC, 120EE0692 approved these changes

2022-10-20 13:20 UTC, merged