feat: add article table
Monday-Morning/project-tahiti pull request #280
Opened 2022-10-15 14:07 UTC by Amal-Mohan-2002

### Your checklist for this pull request

🚨Please review the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [x] Make sure you are making a pull request against the **default branch** (left side). Also you should start _your branch_ off _default branch_.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.
- [x] I have added necessary documentation (if appropriate)

### Linked Issues

Fixes #264 

### Description

Please describe your pull request.

❤️Thank you!

### Post merge checklist

- [x] Follow steps from the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.
- [x] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2022-10-16 11:48 UTC, 120EE0692 requested changes
@Amal-Mohan-2002 make the changes

2022-10-16 11:48 UTC, 120EE0692 commented on client/src/components/article/ArticleTable.js
> +  const columnh = Object.values(table[0]);
@Amal-Mohan-2002 
rename columnh to tableHead or any thing better you can think.

2022-10-16 11:48 UTC, 120EE0692 commented on client/src/components/article/ArticleTable.js
> +          </TableCell>
@Amal-Mohan-2002 no need to use if else here, use [ternary operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator#:~:text=The%20conditional%20(ternary)%20operator%20is,if%20the%20condition%20is%20falsy.) in className, it will work fine

2022-10-16 11:48 UTC, 120EE0692 commented on client/src/components/article/ArticleTable.js
> +          {tdData()}
@Amal-Mohan-2002 
do we need two functions, can't it just be done using only one.

2022-10-16 11:48 UTC, 120EE0692 commented on client/src/components/article/ArticleTable.js
> +            {column.map((v) => {
@Amal-Mohan-2002
 rename v to colData or something more understandable.

2022-10-16 11:48 UTC, 120EE0692 commented on client/src/components/article/ArticleTable.js
> +    // width: '95%'
@Amal-Mohan-2002 
There is no use of this commented code remove this.

2022-11-05 09:32 UTC, 120EE0692 approved these changes

2022-11-05 12:41 UTC, rutajdash approved these changes

2022-11-05 12:42 UTC, merged