refactor[Admin]: change author cards
Monday-Morning/project-tahiti pull request #281
Opened 2022-10-15 14:12 UTC by Anish-Sarawgi

### Your checklist for this pull request

🚨Please review the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [ ] Make sure you are making a pull request against the **default branch** (left side). Also you should start _your branch_ off _default branch_.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.
- [ ] I have added necessary documentation (if appropriate)

### Linked Issues

Fixes

### Description

Please describe your pull request.

❤️Thank you!

### Post merge checklist

- [ ] Follow steps from the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2022-10-20 16:21 UTC, rutajdash requested changes
Please replace the AuthorCard.jsx with AuthorCardNew.jsx
We do not have a need for both.

2022-10-20 18:36 UTC, Anish-Sarawgi commented
> Please replace the AuthorCard.jsx with AuthorCardNew.jsx We do not have a need for both.

I have made the required changes.

2022-10-28 08:51 UTC, rutajdash approved these changes

2022-10-28 08:52 UTC, rutajdash commented
> > Please replace the AuthorCard.jsx with AuthorCardNew.jsx We do not have a need for both.
> 
> I have made the required changes.

Why are the file names still different. Please make them the same and rebase with the latest changes.

2022-10-28 10:18 UTC, rutajdash approved these changes

2022-10-28 10:19 UTC, merged