feat: sac and clubs info page
Monday-Morning/project-tahiti pull request #296
Opened 2022-11-02 13:41 UTC by anish-patro

### Your checklist for this pull request

🚨Please review the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [x] Make sure you are making a pull request against the **default branch** (left side). Also you should start _your branch_ off _default branch_.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.
- [x] I have added necessary documentation (if appropriate)

### Linked Issues 

Fixes #271 

### Description

![Screenshot (34)](https://user-images.githubusercontent.com/105335549/199504408-58615bfe-1bcd-470c-ada5-08f85d0065fe.png)
please describe your pull request.

❤️Thank you!

### Post merge checklist

- [x] Follow steps from the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.
- [x] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2022-11-09 07:44 UTC, 120EE0692 commented
@Anish-Sarawgi please change title of the PR and rebase with the main branch.

2022-11-15 14:10 UTC, 120EE0692 requested changes
@anish-patro code is not at all structured.

2022-11-15 14:10 UTC, 120EE0692 commented on client/src/components/widgets/ClubCards.js
> +      //  padding:'3px'
@anish-patro remove unnecessary comments.

2022-11-15 14:10 UTC, 120EE0692 commented on client/src/components/widgets/ClubInfoNavbar.js
> +  //   </>
@anish-patro why this comment is there?

2022-11-15 14:10 UTC, 120EE0692 commented on client/src/components/widgets/ClubInfoNavbar.js
> +// </div> }
@anish-patro why this comment is there?

2022-11-15 14:10 UTC, 120EE0692 commented on client/src/components/widgets/PostHolder.js
> +        style={{ marginBottom: '5px' }}
@anish-patro no inline styles.

2022-11-15 14:10 UTC, 120EE0692 commented on client/src/components/widgets/PostHolder.js
> +        style={{ marginBottom: '5px' }}
@anish-patro no inline styles

2022-11-15 14:10 UTC, 120EE0692 commented on client/src/components/widgets/PostHolder.js
> +        <Typography style={{ marginLeft: '10px' }} variant='body2'>
@anish-patro no inline styles.

2022-11-15 14:10 UTC, 120EE0692 commented on client/src/components/widgets/SacInfoNavbar.js
> +const SectionNavbar1 = () => {
@anish-patro rename SectionNavbar1 avoid using numbers.

2022-11-15 14:10 UTC, 120EE0692 commented on client/src/components/widgets/SocietyCards.js
> +        <CardContent className={classes.hallDetails}>
@anish-patro hallDetails ?

2022-11-26 08:25 UTC, 120EE0692 commented
@anish-patro please resolve all conversations, if required changes are done.

2022-12-10 19:44 UTC, rutajdash commented
@120EE0692 @anish-patro what is up with this?

2022-12-11 04:39 UTC, 120EE0692 commented
> @120EE0692 @anish-patro what is up with this?

@rutajdash mostly done, only few club content is left. After that good to go.

2022-12-15 03:20 UTC, 120EE0692 requested changes

2022-12-15 03:20 UTC, 120EE0692 commented on client/src/pages/guide.jsx
> +// }
@anish-patro guide page should be redirect to coming soon.

2022-12-15 11:36 UTC, 120EE0692 approved these changes

2022-12-20 10:49 UTC, rutajdash approved these changes

2022-12-20 10:49 UTC, merged