feat: setup firebase emulator
Monday-Morning/project-tahiti pull request #303
Opened 2022-11-07 17:35 UTC by rutajdash

### Your checklist for this pull request

🚨Please review the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [ ] Make sure you are making a pull request against the **default branch** (left side). Also you should start _your branch_ off _default branch_.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.
- [ ] I have added necessary documentation (if appropriate)

### Linked Issues

Fixes

### Description

Please describe your pull request.

❤️Thank you!

### Post merge checklist

- [ ] Follow steps from the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2022-11-08 14:00 UTC, 120EE0692 requested changes

2022-11-08 14:00 UTC, 120EE0692 commented on client/src/config/firebase.js
>  export const firebaseApp = initializeApp(firebaseConfig);
@rutajdash if dev setup this and he does not have the keys, it will show invalid api key error.

2022-11-08 19:33 UTC, rutajdash commented on client/src/config/firebase.js
>  export const firebaseApp = initializeApp(firebaseConfig);
Will make the required arrangements.

2022-11-09 05:35 UTC, 120EE0692 approved these changes

2022-11-12 08:13 UTC, merged