fix(article): add null check for authorName
Monday-Morning/project-tahiti pull request #310
Opened 2022-11-16 18:35 UTC by Shurtu-gal

### Your checklist for this pull request

🚨Please review the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [x] Make sure you are making a pull request against the **default branch** (left side). Also you should start _your branch_ off _default branch_.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.
- [ ] I have added necessary documentation (if appropriate)

### Linked Issues
bug: add null check in authors name #305

Fixes

### Description

Please describe your pull request.

❤️Thank you!

### Post merge checklist

- [ ] Follow steps from the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2022-11-19 09:59 UTC, 120EE0692 approved these changes

2022-11-20 19:56 UTC, rutajdash requested changes

2022-11-20 19:56 UTC, rutajdash commented on client/src/components/article/Header.js
> +                        {name.replace(/ null( |$)/g, '')}
This will fail.
If name is null, it is not of String type and does not have the prototype method replace.

2022-11-20 19:58 UTC, Shurtu-gal commented on client/src/components/article/Header.js
> +                        {name.replace(/ null( |$)/g, '')}
Actually name is being passed in concaneted form like 'Ash null' so replace is being used.

2022-11-20 20:00 UTC, Shurtu-gal commented on client/src/components/article/Header.js
> +                        {name.replace(/ null( |$)/g, '')}
That's why standard null coalescing is not workable.

2022-11-20 20:10 UTC, rutajdash commented on client/src/components/article/Header.js
> +                        {name.replace(/ null( |$)/g, '')}
Ok sure. However, there is a potential edge case where name might entirely be null and using the replace method would cause an error. Use conditional chaining in this scenario or also add a null check.

2022-11-20 20:12 UTC, Shurtu-gal commented on client/src/components/article/Header.js
> +                        {name.replace(/ null( |$)/g, '')}
Will do !  :+1:

2022-11-21 19:32 UTC, rutajdash approved these changes

2022-11-21 19:33 UTC, merged