feat: autocomplete suggestion
Monday-Morning/project-tahiti pull request #311
Opened 2022-11-17 11:59 UTC by 120EE0692

### Your checklist for this pull request

🚨Please review the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [x] Make sure you are making a pull request against the **default branch** (left side). Also you should start _your branch_ off _default branch_.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.
- [x] I have added necessary documentation (if appropriate)

### Linked Issues

Fixes 

### Description
<img width="421" alt="image" src="https://user-images.githubusercontent.com/83752052/202440529-ecfa5f5b-df23-48aa-8f7a-8633ecde20dd.png">

Please describe your pull request.

❤️Thank you!

### Post merge checklist

- [x] Follow steps from the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.
- [x] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2022-11-18 16:50 UTC, rutajdash requested changes

2022-11-18 16:50 UTC, rutajdash commented on client/src/components/marginals/DesktopNavbar.js
> +    console.log(isSearchActive);
```suggestion
```

2022-11-18 16:53 UTC, rutajdash commented
@120EE0692 please resolve conflicts

2022-11-19 08:21 UTC, rutajdash reviewed
There are formatting issues flagged in the checks.

2022-11-19 08:41 UTC, 120EE0692 commented
> There are formatting issues flagged in the checks.

@rutajdash it seems to be something else
<img width="642" alt="image" src="https://user-images.githubusercontent.com/83752052/202842666-d5241c1f-c1ff-4c63-96ae-c34ce7c3d276.png">

2022-11-20 19:54 UTC, rutajdash commented
> > There are formatting issues flagged in the checks.
> 
> @rutajdash it seems to be something else <img alt="image" width="642" src="https://user-images.githubusercontent.com/83752052/202842666-d5241c1f-c1ff-4c63-96ae-c34ce7c3d276.png">

Check the prettier output stage. The script fails when it finds formatting errors.

2022-11-20 19:55 UTC, rutajdash commented
![image](https://user-images.githubusercontent.com/33367546/202923151-0ad7c915-fbd8-46a2-a734-294d91354e2b.png)

There may be more files

2022-11-21 02:54 UTC, 120EE0692 commented
> ![image](https://user-images.githubusercontent.com/33367546/202923151-0ad7c915-fbd8-46a2-a734-294d91354e2b.png)
> 
> There may be more files

<img width="831" alt="image" src="https://user-images.githubusercontent.com/83752052/202953230-3267dbfe-1ad0-45d6-a942-c9747f60d7eb.png">
@rutajdash no formatting issue.

2022-11-21 09:50 UTC, closed without merging