fix: add exception handling to rendering
Monday-Morning/project-tahiti pull request #319
Opened 2022-11-22 21:22 UTC by Shurtu-gal

### Your checklist for this pull request

🚨Please review the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [ ] Make sure you are making a pull request against the **default branch** (left side). Also you should start _your branch_ off _default branch_.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.
- [ ] I have added necessary documentation (if appropriate)

### Linked Issues
#314
Fixes

### Description

Please describe your pull request.

❤️Thank you!

### Post merge checklist

- [ ] Follow steps from the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2022-11-25 09:11 UTC, 120EE0692 commented
@Shurtu-gal this will show 404 page, it would be better if we can get 500 page.

2022-11-25 09:36 UTC, 120EE0692 commented
@Shurtu-gal 
I think this will redirect to page [404](https://mondaymorning.nitrkl.ac.in/404) even in case of error.
Please make sure in case of some error it redirects to page [500](https://mondaymorning.nitrkl.ac.in/500)

2022-12-06 17:31 UTC, 120EE0692 requested changes

2022-12-06 17:31 UTC, 120EE0692 commented on client/src/pages/archive/[...yearAndMonth].jsx
> +        // error: err,
@Shurtu-gal pleasse remove this comment. This addes no value to the code and it's readability. Do this is all the files.

2022-12-06 17:59 UTC, 120EE0692 requested changes

2022-12-06 17:59 UTC, 120EE0692 commented on client/src/pages/article/[...article].jsx
> +      notFound: true,
@Shurtu-gal why notFound?

2022-12-06 17:59 UTC, 120EE0692 commented on client/src/pages/index.jsx
> +      notFound: true,
@Shurtu-gal why notFound and error used here?

2022-12-08 17:17 UTC, 120EE0692 commented on client/src/pages/expressions/[...subCategory].jsx
> +      {!isLoading && !isError && !isFallback ? (
@Shurtu-gal is this change required?

2022-12-09 16:39 UTC, 120EE0692 approved these changes

2022-12-10 19:12 UTC, rutajdash reviewed
Would it be possible to use the 500 error inside the header/head tags? We don't want any page to go without having some headers being passed.

2022-12-10 19:12 UTC, rutajdash commented on client/src/pages/expressions/[...subCategory].jsx
> +    }
Why this block?

2022-12-11 07:17 UTC, Shurtu-gal commented
> Would it be possible to use the 500 error inside the header/head tags? We don't want any page to go without having some headers being passed.

Yes, it's done.

2022-12-11 08:42 UTC, rutajdash approved these changes
Custom error boundaries left for future scope.

2022-12-11 08:42 UTC, rutajdash commented
To be merged soon.

2022-12-11 08:44 UTC, rutajdash requested changes
![image](https://user-images.githubusercontent.com/33367546/206894392-d7142675-5ec4-441e-af64-e7be2f7a63ee.png)

Please fix these issues

2022-12-11 08:58 UTC, 120EE0692 commented
> ![image](https://user-images.githubusercontent.com/33367546/206894392-d7142675-5ec4-441e-af64-e7be2f7a63ee.png)
> 
> Please fix these issues

@Shurtu-gal if there is no prettier issue then do the following steps
1) rename the file 500.jsx to something else, commit and push the changes.
2) then rename it back to 500.jsx, then commit and push.

2022-12-11 09:13 UTC, rutajdash approved these changes

2022-12-11 09:13 UTC, merged