feat: create individual Photostory page
Monday-Morning/project-tahiti pull request #331
Opened 2022-12-02 08:39 UTC by Anish-Sarawgi

### Your checklist for this pull request

🚨Please review the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [ ] Make sure you are making a pull request against the **default branch** (left side). Also you should start _your branch_ off _default branch_.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.
- [ ] I have added necessary documentation (if appropriate)

### Linked Issues

Fixes #322 

### Description

Please describe your pull request.

❤️Thank you!

### Post merge checklist

- [ ] Follow steps from the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2022-12-02 08:54 UTC, 120EE0692 commented
@Anish-Sarawgi the UI/UX is not matching. 
<img width="947" alt="image" src="https://user-images.githubusercontent.com/83752052/205253742-44e18a8a-87b0-4260-9a49-87dc6f924600.png">

The height of side images should be smaller as compare to the image in the center.

2022-12-11 09:06 UTC, 120EE0692 requested changes

2022-12-11 09:06 UTC, 120EE0692 commented on client/src/pages/photostory/[...photostory].jsx
> +  }
@Anish-Sarawgi remove this part.

2022-12-11 09:06 UTC, 120EE0692 commented on client/src/pages/photostory/[...photostory].jsx
> +    photostory: [articleId, articleSlug, _date, oldArticleLink],
@Anish-Sarawgi remove _date and oldArticleLink.

rename articleId to photoStoryId and articleSlug to photoStorySlug

2022-12-11 09:49 UTC, 120EE0692 requested changes
<img width="946" alt="image" src="https://user-images.githubusercontent.com/83752052/206896878-2de73a26-9f1c-40b7-961c-3feacee686ea.png">
@Anish-Sarawgi make code changes so that photo story in the right redirects to photostory page and not to article page.

2022-12-11 09:51 UTC, 120EE0692 requested changes
@Anish-Sarawgi 
<img width="827" alt="image" src="https://user-images.githubusercontent.com/83752052/206896962-5b28079f-c30c-458f-b481-79cfef4c2a46.png">
tags must be dynamic.

2022-12-11 09:52 UTC, 120EE0692 requested changes
<img width="517" alt="image" src="https://user-images.githubusercontent.com/83752052/206896997-80e77ef5-f0fe-4b56-b08e-8fdb0324b817.png">
@undo or comments these changes.

2022-12-11 18:30 UTC, 120EE0692 requested changes

2022-12-11 18:30 UTC, 120EE0692 commented on client/src/assets/placeholder/photostory.js
> +  tags: [{ name: 'BM-BT' }, { name: 'Department' }],
@Anish-Sarawgi why this changes were done.

2022-12-11 18:30 UTC, 120EE0692 commented on client/src/pages/photostory/[...photostory].jsx
> +  const {
@Anish-Sarawgi add try catch / error handling here.

2022-12-11 19:16 UTC, Anish-Sarawgi commented on client/src/assets/placeholder/photostory.js
> +  tags: [{ name: 'BM-BT' }, { name: 'Department' }],
It was used for the proper destructuring of props while using the placeholder data for tags. But as now dynamic tags were used, i think it is of no use.

2022-12-12 03:58 UTC, 120EE0692 requested changes

2022-12-12 03:58 UTC, 120EE0692 commented on client/src/pages/photostory/[...photostory].jsx
> +        isError: true,
@Anish-Sarawgi this will not show page 500 when error occurs.

2022-12-12 03:58 UTC, 120EE0692 commented on client/src/pages/photostory/[...photostory].jsx
>  function PhotostoryPage({ photostory }) {
@Anish-Sarawgi get isError variable from here.

2022-12-12 15:04 UTC, 120EE0692 requested changes

2022-12-12 16:04 UTC, 120EE0692 approved these changes

2022-12-14 07:54 UTC, rutajdash requested changes
@Anish-Sarawgi please screenshots of the latest UI designed.

2022-12-14 07:54 UTC, rutajdash commented on client/src/components/widgets/PhotoCarousel.js
> +const PhotoCarousel = ({ IMAGE, navigator, Text }) => {
The variable `Text` is not following naming conventions. Use lowerCamelCase or all caps.

2022-12-14 08:28 UTC, Anish-Sarawgi commented
> @Anish-Sarawgi please screenshots of the latest UI designed.

I have added the screenshots in the PR description now.

2022-12-20 10:44 UTC, rutajdash approved these changes

2022-12-20 10:44 UTC, merged