feat: show all articles of latest issue
Monday-Morning/project-tahiti pull request #333
Opened 2022-12-04 10:44 UTC by anish-patro

### Your checklist for this pull request

🚨Please review the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [ ] Make sure you are making a pull request against the **default branch** (left side). Also you should start _your branch_ off _default branch_.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.
- [ ] I have added necessary documentation (if appropriate)

### Linked Issues

Fixes #267 

### Description

Please describe your pull request.

❤️Thank you!

### Post merge checklist

- [ ] Follow steps from the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2022-12-04 15:20 UTC, 120EE0692 requested changes

2022-12-04 15:20 UTC, 120EE0692 commented on client/src/screens/Home.js
> +  const tabletMatches = useMediaQuery(theme.breakpoints.down('lg'));
@anish-patro mobMatches is not used. Try to solve this issue by using between.

2022-12-04 15:20 UTC, 120EE0692 commented on client/src/screens/Home.js
> +          </>
@anish-patro I think this can be done in a better way.

example: 
matches ? 3 : 4

2022-12-05 03:47 UTC, 120EE0692 approved these changes

2022-12-10 19:31 UTC, rutajdash commented on client/src/screens/Home.js
> +  const tabletMatches = useMediaQuery(theme.breakpoints.between('sm', 'lg'));
Why do we need to consider a separate value for tablet view at all? The UI adapts fine the same doesn't it?

2022-12-10 20:00 UTC, anish-patro commented on client/src/screens/Home.js
> +  const tabletMatches = useMediaQuery(theme.breakpoints.between('sm', 'lg'));
If we will not use that then it  will look like this in tablet/small laptops view
![Screenshot (88)](https://user-images.githubusercontent.com/105335549/206873194-4eb6bddc-edf6-4100-8ab3-e4cd34ed5fe4.png)

2022-12-10 20:26 UTC, rutajdash commented
@anish-patro resolve all the conflicts please.

2022-12-11 08:39 UTC, merged