feat: add go to archives section in footer
Monday-Morning/project-tahiti pull request #335
Opened 2022-12-05 03:24 UTC by Shurtu-gal

### Your checklist for this pull request

🚨Please review the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [ ] Make sure you are making a pull request against the **default branch** (left side). Also you should start _your branch_ off _default branch_.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.
- [ ] I have added necessary documentation (if appropriate)

### Linked Issues
#307 
Fixes

### Description

Please describe your pull request.

❤️Thank you!

### Post merge checklist

- [ ] Follow steps from the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2022-12-05 03:37 UTC, 120EE0692 requested changes
@Shurtu-gal 

<img width="248" alt="image" src="https://user-images.githubusercontent.com/83752052/205544049-beb57229-6ba9-42ed-9265-9f98a4d06971.png">

please change the font family of all option in the dropdown as given in the figma.

2022-12-05 04:02 UTC, Shurtu-gal commented
> @Shurtu-gal
> 
> <img alt="image" width="248" src="https://user-images.githubusercontent.com/83752052/205544049-betellb57229-6ba9-42ed-9265-9f98a4d06971.png">
> 
> please change the font family of all option in the dropdown as given in the figma.

Can you tell where is the styling for dropdown menu in figma?

2022-12-05 04:05 UTC, 120EE0692 commented
> > @Shurtu-gal
> > 
> > <img alt="image" width="248" src="https://user-images.githubusercontent.com/83752052/205544049-betellb57229-6ba9-42ed-9265-9f98a4d06971.png">
> > 
> > please change the font family of all option in the dropdown as given in the figma.
> 
> Can you tell where is the styling for dropdown menu in figma?

For drop-down menu there is no styling. But make sure the font which used in drop down menu, it should be same as of the placeholder of drop-down.

2022-12-05 08:50 UTC, 120EE0692 approved these changes

2022-12-10 19:22 UTC, rutajdash approved these changes

2022-12-10 19:22 UTC, merged