feat/add student pulse
Monday-Morning/project-tahiti pull request #337
Opened 2022-12-05 10:09 UTC by priyadarshini-silpa

### Your checklist for this pull request

🚨Please review the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [ ] Make sure you are making a pull request against the **default branch** (left side). Also you should start _your branch_ off _default branch_.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.
- [ ] I have added necessary documentation (if appropriate)

### Linked Issues

Fixes

### Description

Please describe your pull request.

❤️Thank you!

### Post merge checklist

- [ ] Follow steps from the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2022-12-05 15:49 UTC, 120EE0692 requested changes
@priyadarshini-silpa 
-> center the poll image in mobile view.
-> add a circle behind the image.

2022-12-05 15:49 UTC, 120EE0692 commented on client/src/components/widgets/Pulse.js
> +  ButtonBase,
@priyadarshini-silpa remove unused components.

2022-12-05 15:49 UTC, 120EE0692 commented on client/src/components/widgets/Pulse.js
>              {console.log()}
remove console.log()

2022-12-08 12:57 UTC, 120EE0692 approved these changes

2022-12-10 19:24 UTC, rutajdash reviewed
@priyadarshini-silpa @120EE0692 are the sizing and formatting issues that were occurring with calendar side by side been all fixed?

2022-12-11 03:39 UTC, 120EE0692 commented
> @priyadarshini-silpa @120EE0692 are the sizing and formatting issues that were occurring with calendar side by side been all fixed?

@rutajdash yes.

2022-12-11 08:22 UTC, merged