feat(events): add calendar component for events page
Monday-Morning/project-tahiti pull request #338
Opened 2022-12-07 12:56 UTC by kanhaiya88628

### Your checklist for this pull request

🚨Please review the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [x] Make sure you are making a pull request against the **default branch** (left side). Also you should start _your branch_ off _default branch_.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.
- [x] I have added necessary documentation (if appropriate)

### Linked Issues

Fixes #324 

### Description

Please describe your pull request.

❤️Thank you!

### Post merge checklist

- [ ] Follow steps from the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2022-12-08 12:46 UTC, 120EE0692 requested changes
<img width="893" alt="image" src="https://user-images.githubusercontent.com/83752052/206448947-f59a70c4-b363-4d21-b60a-da5ee4960a51.png">

@kanhaiya88628 make the following changes
-> Increase the gap between weekdays and the days box. check figma for exact details.

<img width="305" alt="image" src="https://user-images.githubusercontent.com/83752052/206450002-6e8e4bfa-aa47-4a5c-8ad2-5cbe8a1cfc80.png">

-> add a events page which must redirect to coming soon page.

2022-12-08 18:54 UTC, 120EE0692 requested changes

2022-12-08 18:54 UTC, 120EE0692 commented on client/src/pages/events.jsx
> +const AboutPage = () => {
@kanhaiya88628 change it to events page.

2022-12-08 18:54 UTC, 120EE0692 commented on client/src/pages/events.jsx
> +        <title>About | Monday Morning</title>
@kanhaiya88628 change about to events.

2022-12-08 18:54 UTC, 120EE0692 commented on client/src/pages/events.jsx
> +          content='https://mondaymorning.nitrkl.ac.in/about'
@kanhaiya88628 change here as well

2022-12-08 18:54 UTC, 120EE0692 commented on client/src/pages/events.jsx
> +export default AboutPage;
@kanhaiya88628 change here ass well

2022-12-09 16:38 UTC, 120EE0692 approved these changes

2022-12-10 19:32 UTC, rutajdash commented
@120EE0692 since when do we have an events page?

2022-12-10 19:42 UTC, rutajdash reviewed
1. Why was an events page created?
2. Why was an add events component created? That should be added to admin panel, not main app and certainly not open to public.
3. What happened to the home page calendar component?

2022-12-11 03:45 UTC, 120EE0692 commented
> 1. Why was an events page created?
> 2. Why was an add events component created? That should be added to admin panel, not main app and certainly not open to public.
> 3. What happened to the home page calendar component?

@rutajdash 
1. Events page was created to provide information to the general public about all the ongoing events.

We will show calendar as well as event card.
<img width="263" alt="image" src="https://user-images.githubusercontent.com/83752052/206885279-f51a4241-b210-48dd-884d-37fd36290bc1.png">

2. add events component will not be accessible to general public, we will add permission checks.

3. Home page calendar component UI is ready and already merged.

2022-12-11 08:30 UTC, rutajdash commented
> > 1. Why was an events page created?
> > 2. Why was an add events component created? That should be added to admin panel, not main app and certainly not open to public.
> > 3. What happened to the home page calendar component?
> 
> @rutajdash
> 
> 1. Events page was created to provide information to the general public about all the ongoing events.
> 
> We will show calendar as well as event card. <img alt="image" width="263" src="https://user-images.githubusercontent.com/83752052/206885279-f51a4241-b210-48dd-884d-37fd36290bc1.png">
> 
> 2. add events component will not be accessible to general public, we will add permission checks.
> 3. Home page calendar component UI is ready and already merged.

And why do we need an events page?
Considering that the events section is not a focus point of Monday Morning. Simple popups from the calendar on the landing page with minimal event information should suffice in my opinion.
Furthermore, Monday Morning, or rather Project Infinity is partnered with other projects at NITR, few of which focus on the college events aspect.

2022-12-14 04:23 UTC, 120EE0692 commented
@kanhaiya88628 changes done?

2022-12-14 17:03 UTC, 120EE0692 approved these changes

2022-12-20 10:48 UTC, rutajdash reviewed
Why was chart.js removed from the package dependencies?

2023-01-04 12:50 UTC, rutajdash approved these changes

2023-01-04 12:50 UTC, merged