feat(home): integrate youtube data api to fetch video meta data from a playlist
Monday-Morning/project-tahiti pull request #343
Opened 2022-12-09 09:57 UTC by Shurtu-gal

### Your checklist for this pull request

🚨Please review the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [ ] Make sure you are making a pull request against the **default branch** (left side). Also you should start _your branch_ off _default branch_.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.
- [ ] I have added necessary documentation (if appropriate)

### Linked Issues
#320 
Fixes

### Description

Please describe your pull request.

❤️Thank you!

### Post merge checklist

- [ ] Follow steps from the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2022-12-09 16:01 UTC, 120EE0692 requested changes

2022-12-10 16:36 UTC, 120EE0692 requested changes

2022-12-10 16:36 UTC, 120EE0692 commented on client/src/screens/Home.js
> +          <SocialMedia youtubeLink={youtubeLink} />
@Shurtu-gal please comments this out.

2022-12-10 16:36 UTC, 120EE0692 commented on client/src/pages/index.jsx
> +function HomePage({ issues, squiggles, YoutubeLink }) {
@Shurtu-gal use camel case

2022-12-10 16:36 UTC, 120EE0692 commented on client/src/pages/index.jsx
> +            youtubeLink={YoutubeLink}
use camel case

2022-12-10 16:36 UTC, 120EE0692 commented on client/src/pages/index.jsx
> +  const YoutubeLink = youtubeData.items.map(
use camel case

2022-12-10 16:36 UTC, 120EE0692 commented on client/src/pages/index.jsx
> +      YoutubeLink,
use camel case

2022-12-10 17:09 UTC, 120EE0692 approved these changes

2022-12-10 17:10 UTC, 120EE0692 commented
@rutajdash env keys are used in server side.

2022-12-10 19:39 UTC, rutajdash requested changes
This is good work.

2022-12-10 19:39 UTC, rutajdash commented on client/env/.env.sample
> +NEXT_PUBLIC_YOUTUBE_API_KEY=some-api-key
Remove `NEXT_PUBLIC_`
As it is used server side, no need to expose credentials to the public.
Refactor in all places in code.

2022-12-11 04:06 UTC, Shurtu-gal commented on client/env/.env.sample
> +NEXT_PUBLIC_YOUTUBE_API_KEY=some-api-key
Sure

2022-12-11 05:03 UTC, Shurtu-gal commented on client/env/.env.sample
> +NEXT_PUBLIC_YOUTUBE_API_KEY=some-api-key
> Remove `NEXT_PUBLIC_` As it is used server side, no need to expose credentials to the public. Refactor in all places in code.

Playlist Id should remain public or not?

2022-12-11 05:27 UTC, 120EE0692 commented on client/env/.env.sample
> +NEXT_PUBLIC_YOUTUBE_API_KEY=some-api-key
> > Remove `NEXT_PUBLIC_` As it is used server side, no need to expose credentials to the public. Refactor in all places in code.
> 
> Playlist Id should remain public or not?

Playlist id is not public.

2022-12-11 08:37 UTC, rutajdash requested changes

2022-12-11 08:37 UTC, rutajdash commented on client/src/components/homepage/SocialMedia.js
> +>>>>>>> eb75993 (fix: styling issues, camelCase)
Same

2022-12-11 08:37 UTC, rutajdash commented on client/src/components/homepage/SocialMedia.js
> +=======
Why were unresolved conflicts pushed?

2022-12-11 08:37 UTC, rutajdash commented on client/src/components/homepage/SocialMedia.js
> +>>>>>>> eb75993 (fix: styling issues, camelCase)
Same

2022-12-11 08:37 UTC, rutajdash commented on client/src/pages/index.jsx
> +  const youtubeLink = youtubeData.items.map(
If this variable contains an array of data, make it a plural like `youtubeLinks` and then refactor everywhere.

2022-12-11 09:14 UTC, rutajdash approved these changes

2022-12-11 09:15 UTC, Shurtu-gal commented
> @Shurtu-gal please resolve conflicts

Sure

2022-12-11 09:55 UTC, rutajdash approved these changes

2022-12-11 09:55 UTC, merged