feat(expressions): add Photostory in Expressions Page
Monday-Morning/project-tahiti pull request #352
Opened 2022-12-14 04:38 UTC by Anish-Sarawgi

### Your checklist for this pull request

🚨Please review the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [ ] Make sure you are making a pull request against the **default branch** (left side). Also you should start _your branch_ off _default branch_.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.
- [ ] I have added necessary documentation (if appropriate)

### Linked Issues

Fixes

### Description

Please describe your pull request.

❤️Thank you!

### Post merge checklist

- [ ] Follow steps from the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2022-12-14 06:36 UTC, 120EE0692 requested changes
@Anish-Sarawgi nice work but on clicking these photostory it should go to photostory page not the article page.

<img width="305" alt="image" src="https://user-images.githubusercontent.com/83752052/207523954-f3aae7e4-a4be-49b9-8244-4ceb601d8de1.png">

2022-12-14 10:15 UTC, 120EE0692 commented on client/src/components/widgets/article/RegularArticleCard.js
> +        }
@Anish-Sarawgi here also

2022-12-14 13:49 UTC, 120EE0692 approved these changes

2022-12-20 10:46 UTC, rutajdash approved these changes

2022-12-20 10:46 UTC, merged