fix: add null check for article
Monday-Morning/project-tahiti pull request #370
Opened 2022-12-22 12:41 UTC by Shurtu-gal

### Your checklist for this pull request

🚨Please review the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [ ] Make sure you are making a pull request against the **default branch** (left side). Also you should start _your branch_ off _default branch_.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.
- [ ] I have added necessary documentation (if appropriate)

### Linked Issues

Fixes

### Description

Please describe your pull request.

❤️Thank you!

### Post merge checklist

- [ ] Follow steps from the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2022-12-23 12:04 UTC, 120EE0692 approved these changes

2022-12-26 16:26 UTC, 120EE0692 requested changes

2022-12-26 16:26 UTC, 120EE0692 commented on client/src/screens/Home.js
> +          {articles.length >= (!tabletMatches ? 9 : 12) && (
@Shurtu-gal I this this will not work, for example we have 13 articles in the articles array , then again empty space will be created.

2022-12-28 12:53 UTC, 120EE0692 approved these changes

2023-01-04 13:53 UTC, Shurtu-gal commented on client/src/pages/live.jsx
> +
Due to merging of PR #391.
It has been removed now.

2023-01-04 13:59 UTC, rutajdash approved these changes

2023-01-04 13:59 UTC, merged