feat: create user profile page
Monday-Morning/project-tahiti pull request #371
Opened 2022-12-22 14:48 UTC by anish-patro

### Your checklist for this pull request

🚨Please review the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [ ] Make sure you are making a pull request against the **default branch** (left side). Also you should start _your branch_ off _default branch_.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.
- [ ] I have added necessary documentation (if appropriate)

### Linked Issues

Fixes #329 

### Description

Please describe your pull request.

❤️Thank you!

### Post merge checklist

- [ ] Follow steps from the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2022-12-23 12:43 UTC, 120EE0692 commented
@anish-patro add images of your work in the description.

2022-12-23 12:54 UTC, 120EE0692 requested changes
<img width="490" alt="image" src="https://user-images.githubusercontent.com/83752052/209339396-d0db6071-de0e-4075-8461-0c6a1bb711d8.png">
@anish-patro add a [container](https://mui.com/material-ui/react-container/) component, around the user profile.

2022-12-23 14:28 UTC, anish-patro commented
> @anish-patro add images of your work in the description

> @anish-patro add images of your work in the description.

2023-01-07 05:58 UTC, sambit-sankalp requested changes

2023-01-07 05:58 UTC, sambit-sankalp commented on client/src/screens/UserProfile.js
> +  selectedOptionM: {
Don't use random names to declare classes.

2023-08-06 19:26 UTC, rutajdash commented
@sambit-sankalp @120EE0692 please proceed with this ASAP.

2023-10-15 12:50 UTC, closed without merging