feat(guide): add mini print carousel
Monday-Morning/project-tahiti pull request #374
Opened 2022-12-23 14:41 UTC by Anish-Sarawgi

### Your checklist for this pull request

🚨Please review the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [ ] Make sure you are making a pull request against the **default branch** (left side). Also you should start _your branch_ off _default branch_.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.
- [ ] I have added necessary documentation (if appropriate)

### Linked Issues

Fixes

### Description

Please describe your pull request.

❤️Thank you!

### Post merge checklist

- [ ] Follow steps from the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2022-12-25 11:27 UTC, 120EE0692 requested changes
@Anish-Sarawgi on clicking back to health and info page it should re direct to the guide page.

2022-12-25 11:27 UTC, 120EE0692 commented on client/src/assets/placeholder/guide.js
>      'NITR-101',
@Anish-Sarawgi comment this as well.

2023-01-04 14:22 UTC, 120EE0692 approved these changes

2023-01-04 14:24 UTC, 120EE0692 commented
@rutajdash ss for reference

<img width="206" alt="image" src="https://user-images.githubusercontent.com/83752052/210575889-782c526a-3e1b-44c0-8fca-0861c02ef4af.png">

<img width="236" alt="image" src="https://user-images.githubusercontent.com/83752052/210576000-85701236-914d-470d-8d38-3b330a4da408.png">

2023-01-04 21:03 UTC, rutajdash requested changes

2023-01-04 21:03 UTC, rutajdash commented on client/src/components/guide/Carousel.js
> +  };
This is not efficient code. The three values should be calculable from total slides and current slide values.

2023-01-04 21:03 UTC, rutajdash commented on client/src/components/guide/Options.js
>          </span>
Can the design here be improved in any way? Like maybe a button instead or something?

2023-01-04 21:03 UTC, rutajdash commented on client/src/pages/guide.jsx
> -
@120EE0692  Will this PR mark the completion of the guide page (with integration)?

2023-01-05 07:27 UTC, 120EE0692 commented on client/src/pages/guide.jsx
> -
@rutajdash this will not complete few things still left, but as of now this page can be out, with the static data.

2023-01-05 17:54 UTC, Anish-Sarawgi commented on client/src/components/guide/Carousel.js
> +  };
Changes done.

2023-01-05 18:55 UTC, rutajdash requested changes

2023-01-05 18:55 UTC, rutajdash commented on client/src/pages/live.jsx
> +
Please remove this code.

2023-01-05 18:59 UTC, Anish-Sarawgi commented on client/src/pages/live.jsx
> +
Done.

2023-01-05 18:59 UTC, rutajdash approved these changes

2023-01-05 19:10 UTC, 120EE0692 approved these changes

2023-01-05 21:51 UTC, merged