fix: live and department links
Monday-Morning/project-tahiti pull request #387
Opened 2022-12-28 08:20 UTC by Shurtu-gal

### Your checklist for this pull request

🚨Please review the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [x] Make sure you are making a pull request against the **default branch** (left side). Also you should start _your branch_ off _default branch_.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.
- [ ] I have added necessary documentation (if appropriate)

### Linked Issues

Fixes

### Description

Please describe your pull request.

❤️Thank you!

### Post merge checklist

- [x] Follow steps from the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2022-12-28 12:29 UTC, 120EE0692 approved these changes

2023-01-03 10:58 UTC, sambit-sankalp requested changes
Make sure to run prettier before committing your code.

2023-01-03 10:58 UTC, sambit-sankalp commented on client/src/components/widgets/SubCategoryLink.js
> +
Remove these unnecessary lines.

2023-01-03 10:58 UTC, sambit-sankalp commented on client/src/components/widgets/SubCategoryLink.js
> +
same here

2023-01-03 10:58 UTC, sambit-sankalp commented on client/src/components/widgets/SubCategoryLink.js
> +
same here

2023-01-04 06:11 UTC, sambit-sankalp approved these changes
GTG

2023-01-04 13:26 UTC, rutajdash commented on client/src/pages/live.jsx
> +
Why is this code here?

2023-01-04 13:46 UTC, Shurtu-gal commented on client/src/pages/live.jsx
> +
Due to merging of PR #391 .

It has been removed now.

2023-01-04 13:48 UTC, merged