feat: add onboarding pagination
Monday-Morning/project-tahiti pull request #388
Opened 2022-12-28 20:07 UTC by Shurtu-gal

### Your checklist for this pull request

🚨Please review the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [x] Make sure you are making a pull request against the **default branch** (left side). Also you should start _your branch_ off _default branch_.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.
- [ ] I have added necessary documentation (if appropriate)

### Linked Issues

Fixes #380 

### Description

Please describe your pull request.

❤️Thank you!

### Post merge checklist

- [x] Follow steps from the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2022-12-29 13:58 UTC, 120EE0692 requested changes
@Shurtu-gal can you make the onboarding experience smooth for mobile users also.

2023-01-03 18:24 UTC, Shurtu-gal commented
> @Shurtu-gal can you make the onboarding experience smooth for mobile users also.

Done

2023-01-04 16:03 UTC, 120EE0692 requested changes
<img width="519" alt="image" src="https://user-images.githubusercontent.com/83752052/210597069-bd47f4a7-30e3-4a64-ba71-faad83f59ce0.png">
make the text inside the button inline, refer to figma.

figma:
<img width="424" alt="image" src="https://user-images.githubusercontent.com/83752052/210597324-09e5b1ea-2e0c-43cd-87cc-071752ed2939.png">

2023-01-04 17:03 UTC, Shurtu-gal commented
Done 👍🏻

2023-01-04 17:15 UTC, 120EE0692 requested changes

2023-01-04 17:15 UTC, 120EE0692 commented on client/src/components/onboarding/stages/Welcome.js
> +    // height: '56px',
@Shurtu-gal remove this if not required

2023-01-04 17:16 UTC, Shurtu-gal commented on client/src/components/onboarding/stages/Welcome.js
> +    // height: '56px',
Sure

2023-01-04 17:29 UTC, 120EE0692 approved these changes

2023-01-04 20:48 UTC, rutajdash approved these changes
Great job with the pagination CSS!

2023-01-04 20:48 UTC, merged