feat: add app recommender
Monday-Morning/project-tahiti pull request #398
Opened 2023-01-12 18:45 UTC by Shurtu-gal

### Your checklist for this pull request

🚨Please review the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [x] Make sure you are making a pull request against the **default branch** (left side). Also you should start _your branch_ off _default branch_.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.
- [x] I have added necessary documentation (if appropriate)

### Linked Issues

Fixes #397 

### Description
## Screenshots :-

<img src="https://user-images.githubusercontent.com/100484401/212152014-0e3267dd-9442-4664-afe5-78f421f01337.png" width=250/> <img src="https://user-images.githubusercontent.com/100484401/212152026-f810c3de-01cb-49dc-a86c-688e13370f10.png" width=250/>  <img src="https://user-images.githubusercontent.com/100484401/212152032-d1a802d6-5b33-4740-97ff-e1e072e56b5d.png" width=250/> <img src="https://user-images.githubusercontent.com/100484401/212152037-90c4e649-67d3-4bdf-a992-45fa6bc548aa.png" width=250/> 

### Post merge checklist

- [x] Follow steps from the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.
- [x] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2023-01-16 14:13 UTC, 120EE0692 requested changes

2023-01-16 14:13 UTC, 120EE0692 commented on client/src/components/marginals/Footer.js
> +      <AppRecommender />
@Shurtu-gal for now comment this.

2023-01-16 14:13 UTC, 120EE0692 commented on client/src/components/marginals/Footer.js
> +import AppRecommender from '../widgets/AppRecomender';
@Shurtu-gal for now comment this.

2023-01-18 13:52 UTC, 120EE0692 requested changes
@Shurtu-gal run prettier in all files, in which you make changes.

2023-01-23 11:09 UTC, rutajdash requested changes
1. Is there any way to check if the user already has the app installed?

2. Can we call on the app instead of a Play Store link? As far as I know, calling on an app to open in Android goes to the app or defaults to the same app's play store page. Find how it is done.

3. We also need to check OS before showing this instead of browser type because it should only appear on Android for now.

2023-01-23 11:09 UTC, rutajdash commented on client/src/assets/placeholder/appRecommender.js
> +      link: 'https://play.google.com/',
Please update this to the correct link.

2023-01-23 11:09 UTC, rutajdash commented on client/src/assets/placeholder/appRecommender.js
> +    },
Comment out safari as we do not have and iOS or macOS app at the moment.

2023-01-23 11:12 UTC, rutajdash commented
Check this out -
https://stackoverflow.com/questions/2958701/launch-custom-android-application-from-android-browser

2023-01-23 11:17 UTC, Shurtu-gal commented on client/src/assets/placeholder/appRecommender.js
> +    },
Yeah, Chrome, Brave and Edge are the major browsers being used on Android devices currently.

2023-01-23 11:17 UTC, Shurtu-gal commented on client/src/assets/placeholder/appRecommender.js
> +    },
Okay

2023-01-23 11:18 UTC, Shurtu-gal commented on client/src/assets/placeholder/appRecommender.js
> +      link: 'https://play.google.com/',
Sure

2023-01-23 14:19 UTC, Shurtu-gal commented
Currently, links to "https://mondaymorning.nitrkl.ac.in/article" are being redirected to the app.
But when it is not installed it is redirecting to the website.

2023-01-23 14:21 UTC, Shurtu-gal commented
navigator.getInstalledRelatedApps() API can be used for checking if the app is installed.
It is supported on Chrome Android.

2023-01-24 09:36 UTC, rutajdash commented
> navigator.getInstalledRelatedApps() API can be used for checking if the app is installed.
> It is supported on Chrome Android.

@120EE0692 
It would be good to implement this too I guess? Then we can call the app instead of going to playstore always.

2024-01-13 06:38 UTC, Shurtu-gal commented
@rutajdash @120EE0692 is this still needed? Else it can be closed I guess.

2024-01-13 06:53 UTC, 120EE0692 commented
> @rutajdash @120EE0692 is this still needed? Else it can be closed I guess.

This is required.

2024-04-16 20:56 UTC, Shurtu-gal commented
Closing this as `not-planned`.

2024-04-16 20:56 UTC, closed without merging