fix: og tags of portfolio
Monday-Morning/project-tahiti pull request #400
Opened 2023-01-14 12:14 UTC by anish-patro

### Your checklist for this pull request

🚨Please review the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [ ] Make sure you are making a pull request against the **default branch** (left side). Also you should start _your branch_ off _default branch_.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.
- [ ] I have added necessary documentation (if appropriate)

### Linked Issues

Fixes #399 

### Description

Please describe your pull request.

❤️Thank you!

### Post merge checklist

- [ ] Follow steps from the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2023-01-16 14:09 UTC, 120EE0692 requested changes
@anish-patro add the same check in the title as well.

2023-01-16 14:09 UTC, 120EE0692 commented on client/src/pages/portfolio/[...userId].jsx
> +          content={`${firstName + ' ' + lastName} | Monday Morning`}
@anish-patro add a condition check lastName should not be null or undefined.

2023-01-26 10:45 UTC, sambit-sankalp commented
@anish-patro updates on the changes requested??

2023-02-01 11:22 UTC, 120EE0692 approved these changes

2023-02-03 11:48 UTC, rutajdash approved these changes

2023-02-03 11:48 UTC, rutajdash commented
@anish-patro please update the branch with latest commits

2023-02-04 11:38 UTC, sambit-sankalp approved these changes

2023-02-04 12:08 UTC, merged