Hall Info Page
Monday-Morning/project-tahiti pull request #401
Opened 2023-01-14 12:38 UTC by Amal-Mohan-2002

### Your checklist for this pull request

🚨Please review the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [x] Make sure you are making a pull request against the **default branch** (left side). Also you should start _your branch_ off _default branch_.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.
- [x] I have added necessary documentation (if appropriate)

### Linked Issues

Fixes #168 

### Description
Hall Images
Please describe your pull request.

❤️Thank you!

### Post merge checklist

- [ ] Follow steps from the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2023-01-15 04:54 UTC, 120EE0692 requested changes
@Amal-Mohan-2002 change title of the PR to feat: add hall page

2023-01-15 04:54 UTC, 120EE0692 commented on client/src/components/article/ArticleTable.js
> +
@Amal-Mohan-2002 why changes here please undo this.

2023-01-15 04:54 UTC, 120EE0692 commented on client/src/components/hallInfo/Info.js
> +                </div> */}
@Amal-Mohan-2002 remove these comment if of no use.

2023-01-15 04:54 UTC, 120EE0692 commented on client/src/components/hallInfo/Info.js
> +  },
@Amal-Mohan-2002 remove this if of no use.

2023-01-15 04:54 UTC, 120EE0692 commented on client/src/components/hallInfo/Info.js
> +  },
@Amal-Mohan-2002 remove this if of no use.

2023-01-16 13:59 UTC, Amal-Mohan-2002 commented on client/src/components/hallInfo/Info.js
> +                </div> */}
This part renders the HNC section.
Should I remove this?

2023-01-18 13:44 UTC, 120EE0692 requested changes

2023-01-18 13:44 UTC, 120EE0692 commented on client/src/components/article/ArticleTable.js
> +}));
@Amal-Mohan-2002 undo this change.

2023-01-18 13:46 UTC, 120EE0692 requested changes

2023-01-18 13:46 UTC, 120EE0692 commented on client/src/components/widgets/DropDownCard.js
> +}));
@Amal-Mohan-2002 run prettier in this file

2023-01-18 13:46 UTC, 120EE0692 commented on client/src/pages/hallInfo.jsx
> +export default HallInfos;
@Amal-Mohan-2002 run prettier in this file.

2023-01-18 13:46 UTC, 120EE0692 commented on client/src/screens/HallInfo.js
> +}));
@Amal-Mohan-2002 run prettier in this file as well.

2023-01-26 10:44 UTC, sambit-sankalp commented
@Amal-Mohan-2002, update on this PR?

2023-01-31 06:11 UTC, 120EE0692 commented on client/src/assets/placeholder/hallInfo.js
> +      title: 'Mokshagundam Visvesvaraya (MV) Hall of Residence',
@Amal-Mohan-2002 remove (MV) only keep 
Mokshagundam Visvesvaraya Hall of Residence.

2023-02-01 12:40 UTC, 120EE0692 commented
@Amal-Mohan-2002 make to write your commit message in small caps.

2023-02-01 12:41 UTC, 120EE0692 approved these changes

2023-02-03 08:36 UTC, sambit-sankalp approved these changes
GTG

2023-02-03 11:52 UTC, rutajdash approved these changes

2023-02-03 11:53 UTC, rutajdash commented
@Amal-Mohan-2002 please update your branch with latest code

2023-02-05 02:35 UTC, 120EE0692 approved these changes

2023-02-05 02:36 UTC, merged