feat: add dark theme context
Monday-Morning/project-tahiti pull request #403
Opened 2023-01-18 11:33 UTC by Shurtu-gal

### Your checklist for this pull request

🚨Please review the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [x] Make sure you are making a pull request against the **default branch** (left side). Also you should start _your branch_ off _default branch_.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.
- [x] I have added necessary documentation (if appropriate)

### Linked Issues

Fixes #402 

### Description
 - Current Changing time :- 2000hrs 

❤️Thank you!

### Post merge checklist

- [x] Follow steps from the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.
- [x] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2023-01-18 13:42 UTC, 120EE0692 requested changes
@Shurtu-gal for now add a logo in the navbar to switch the theme.

image for reference
<img width="301" alt="image" src="https://user-images.githubusercontent.com/83752052/213186754-b8c40764-548f-4bca-89af-dcd5c8400166.png">

2023-01-18 13:42 UTC, 120EE0692 commented on client/src/context/ThemeContext.jsx
> +} from 'react';
@Shurtu-gal check the code is prettier checked pass or not?

2023-01-18 13:42 UTC, 120EE0692 commented on client/src/pages/_app.jsx
> +} from 'react';
@Shurtu-gal check here as well.

2023-01-20 09:30 UTC, 120EE0692 requested changes
@Shurtu-gal add this icon on left side, and make sure to keep left aligned with the black logo.
<img width="893" alt="image" src="https://user-images.githubusercontent.com/83752052/213658325-fe103136-e68c-444f-b80e-4a517806d3bd.png">

2023-01-20 12:22 UTC, Shurtu-gal commented
> @Shurtu-gal add this icon on left side, and make sure to keep left aligned with the black logo. <img alt="image" width="893" src="https://user-images.githubusercontent.com/83752052/213658325-fe103136-e68c-444f-b80e-4a517806d3bd.png">

Done

2023-01-21 03:50 UTC, 120EE0692 approved these changes

2023-01-21 03:51 UTC, 120EE0692 commented
@rutajdash merge this code in a new side branch.

2023-01-23 11:18 UTC, rutajdash reviewed
Please attach multiple screenshots or a comprehensive video showing the dark mode view on all pages and the toggle animation.

2023-01-23 11:24 UTC, 120EE0692 commented
> Please attach multiple screenshots or a comprehensive video showing the dark mode view on all pages and the toggle animation.

We have just created a context to maintain and switch the theme.

For switching a button is placed in the navbar. 

Currently the plan is to merge the pull request in a side branch and develop dark theme page by page there.

2023-01-23 13:16 UTC, Shurtu-gal commented
> Please attach multiple screenshots or a comprehensive video showing the dark mode view on all pages and the toggle animation.
[Screencast from 23-01-23 06:41:54 PM IST.webm](https://user-images.githubusercontent.com/100484401/214048693-dca96618-3db7-4b6c-ae12-fe96d0e2e6bd.webm)

Currently, only context and button have been made.

2023-01-24 09:33 UTC, rutajdash commented
> > Please attach multiple screenshots or a comprehensive video showing the dark mode view on all pages and the toggle animation.
> 
> We have just created a context to maintain and switch the theme.
> 
> For switching a button is placed in the navbar. 
> 
> Currently the plan is to merge the pull request in a side branch and develop dark theme page by page there.

Very well. Please create branch and switch this PRs merge branch.

2023-01-24 11:52 UTC, rutajdash approved these changes

2023-01-24 11:53 UTC, merged